before_install:
 - . port/travis-ci/travis-functions.sh
 - init_travis
 - wrapper init_env_vars
 - wrapper init_perl
 # for agrep package:
 - echo "deb http://de.archive.ubuntu.com/ubuntu/ precise multiverse" | sudo tee -a /etc/apt/sources.list
 - wrapper init_apt
 - wrapper install_non_perl_dependencies
 - wrapper install_perl_testonly_dependencies
 - wrapper install_perl_58_dependencies
 - wrapper install_cpan_hacks
 - wrapper install_webserver_dependencies
install:
 - wrapper install_perl_dependencies
before_script:
 - wrapper init_cgi_config
 - wrapper fix_cgis
 - wrapper init_webserver_config
 - wrapper start_webserver
 - wrapper start_xserver
 - wrapper init_webserver_environment
 - wrapper init_data
script:
 - perl Makefile.PL && make test HARNESS_OPTIONS=j4
language: perl
matrix:
  include:
    - perl: "5.14"
      env: USE_MODPERL=1 USE_SYSTEM_PERL=1
# perl 5.20 is currently broken (see https://github.com/travis-ci/travis-ci/issues/5226)
    - perl: "5.20-extras"
      env: BBBIKE_TEST_SKIP_MODPERL=1
    - perl: "5.18"
      env: BBBIKE_TEST_SKIP_MODPERL=1 BBBIKE_TEST_GUI=1
    - perl: "5.14"
      env: BBBIKE_TEST_SKIP_MODPERL=1
    - perl: "5.10"
      env: BBBIKE_TEST_SKIP_MODPERL=1
    - perl: "5.8"
      env: BBBIKE_TEST_SKIP_MODPERL=1
    - perl: "5.20-shrplib"
      env: USE_MODPERL=1
