language: c
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env:
       - MY_OS=trusty

addons:
 apt:
  packages:
   - make

before_install:
  - git clone --depth=50 --branch=world https://github.com/wosch/bbbike-world.git world
  - . ./world/etc/env/dot.bbbikerc 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./world/travis/travis-init.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libdata-random-perl; fi # ????
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y bbbike-world; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java; fi # downgrade to java7

before_script:
 - true

script:
 - make -f world/Makefile.osm create-bbbike-web-symlinks
 - make debian-bootstrap
 - make update-files
 - world/t/stale-symlinks.t 
 - world/t/convert.t
 #- make travis

