before_install:
 - sudo apt-get update -qq
# Reasons for the following dependencies
# - freebsd-buildutils:     provides freebsd-make resp. fmake
# - libproj-dev + proj-bin: prerequisites for Geo::Proj4
# - libdb-dev:              prerequisite for DB_File
# - agrep:                  needed as String::Approx alternative
# - libgd2-xpm-dev:         prerequisite for GD
# - ttf-bitstream-vera + ttf-dejavu: fonts e.g. for BBBikeDraw::GD
# - xvfb + twm:             some optional tests require an X server
# - rhino:                  javascript tests
 - sudo apt-get install -qq freebsd-buildutils libproj-dev proj-bin libdb-dev agrep libgd2-xpm-dev ttf-bitstream-vera ttf-dejavu gpsbabel xvfb twm rhino
# Some CPAN modules not mentioned in Makefile.PL, usually for testing only
 - cpanm --quiet --notest Test::LectroTest Email::MIME HTML::TreeBuilder::XPath
# DBD::XBase versions between 1.00..1.05 explicitely want Perl 5.10.0 as a minimum. See https://rt.cpan.org/Ticket/Display.html?id=88873
 - '[ "$PERLBREW_PERL" = "5.8" ] && cpanm --quiet --notest DBD::XBase~"!=1.00, !=1.01, !=1.02, !=1.03, !=1.04, !=1.05" || true'
# Perl 5.8.9's File::Path has a version with underscores, and this is causing warnings and failures in the test suite
 - '[ "$PERLBREW_PERL" = "5.8" ] && cpanm --quiet --notest File::Path || true'
# Additional psgi dependencies
 - cpanm --quiet --notest Plack CGI::Emulate::PSGI CGI::Compile Starman Plack::Middleware::Rewrite
before_script:
 - (cd cgi && ln -snf bbbike-debian-no-mapserver.cgi.config bbbike.cgi.config)
 - (cd cgi && ln -snf bbbike2-travis.cgi.config bbbike2.cgi.config)
 - (cd cgi && make symlinks fix-permissions fixin-shebangs)
 - sudo -E `which plackup` --server=Starman --env=test --port=80 cgi/bbbike.psgi &
 - Xvfb :123 &
 - (sleep 10; env DISPLAY=:123 twm) &
 - (sleep 5; lwp-request -m GET "http://localhost/bbbike/cgi/bbbike.cgi?init_environment=1")
env:
 - DISPLAY=:123 BBBIKE_LONG_TESTS=1 BBBIKE_TEST_SKIP_MAPSERVER=1
language: perl
perl:
  - "5.18"
  - "5.14"
  - "5.10"
  - "5.8"
