before_install:
 - . port/travis-ci/travis-functions.sh
 - init_travis
 - wrapper init_env_vars
 - wrapper init_perl
 - wrapper init_apt
 - wrapper install_non_perl_dependencies
 - wrapper install_perl_testonly_dependencies
 - wrapper install_perl_58_dependencies
 - wrapper install_cpan_hacks
 - wrapper install_webserver_dependencies
install:
 - wrapper install_perl_dependencies
before_script:
 - wrapper init_cgi_config
 - wrapper fix_cgis
 - wrapper init_webserver_config
 - wrapper start_webserver
 - wrapper start_xserver
 - wrapper init_data
env:
 - BBBIKE_TEST_SKIP_MODPERL=1
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.14"
  - "5.10"
  - "5.8"
matrix:
  include:
    - perl: 5.20-shrplib
      env: USE_MODPERL=1
    - perl: 5.14
      env: USE_MODPERL=1 USE_SYSTEM_PERL=1
