branches:
  except:
    - /travis/
skip_tags: true
shallow_clone: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%\Task\BBBike\windist
  - cpanm --installdeps .
# For building ext and additional tests
  - cpanm Inline::C XBase Date::Calc Image::ExifTool HTML::FormatText Object::Realize::Later DB_File::Lock
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%

build_script:
  - perl Makefile.PL
  - cd ext
  - dmake -f DMakefile ext
  - cd ..
  - cd t
  - dmake test-on-windows
