###############################################################
# Copyright (c) 2015 Wolfram Schneider, http://bbbike.org
#
# bootstrapping for bbbike-world for jenkins

jenkins-checkout-world:
	if ! test -d world; then \
  	  git clone https://github.com/wosch/bbbike-world.git world; \
	else \
  	  ( cd world; git pull ); \
	fi

help:
	@echo ""
	@echo "usage: make [ targets ... ]"
	@echo ""
	@echo "  [ help | jenkins-checkout-world ]"

