###############################################################
# Copyright (c) 2015 Wolfram Schneider, http://bbbike.org
#
# bootstrapping for bbbike-world

git_clone_opt="-q"

checkout-world:
	if ! test -d world; then \
  	  git clone $git_clone_opt git@github.com:wosch/bbbike-world.git world; \
	else \
  	  ( cd world; git pull ); \
	fi

help:
	@echo ""
	@echo "usage: make [ targets ... ]"
	@echo ""
	@echo "  [ help | checkout-world ]"

