name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.add_name }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
## XXX windows not yet working, macos not tested --- TODO
       include:
         - os:                       'ubuntu-20.04'
           add_name:                 '+ gui tests'
           bbbike_test_gui:          1
           use_modperl:              0
           bbbike_test_skip_modperl: 1
         - os:                       'ubuntu-18.04'
           add_name:                 ''
           bbbike_test_gui:          0
           use_modperl:              0
           bbbike_test_skip_modperl: 1
         - os:                       'ubuntu-16.04'
           add_name:                 '+ mod_perl'
           bbbike_test_gui:          0
           use_modperl:              1
           bbbike_test_skip_modperl: 0

    steps:
    - name: apt hacks
      # the already installed libgd3 conflicts with libgd-dev to be installed
      # also, /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
      run: |
        sudo rm -f /etc/apt/sources.list.d/*.list
        sudo apt-get update -qq
        sudo apt-get remove -y libgd3 nginx
      if: "startsWith(matrix.os, 'ubuntu-')"
    - uses: actions/checkout@v2
    - name: Build and test
      env:
        USE_SYSTEM_PERL:          1
        USE_MODPERL:              ${{ matrix.use_modperl }}
        BBBIKE_TEST_SKIP_MODPERL: ${{ matrix.bbbike_test_skip_modperl }}
        BBBIKE_TEST_GUI:          ${{ matrix.bbbike_test_gui }}
      run: |
        set -e
        export TRAVIS_BUILD_DIR=$GITHUB_WORKSPACE
        # before_install:
        . port/travis-ci/travis-functions.sh
        init_travis
        wrapper init_env_vars
        wrapper init_perl
        wrapper init_apt
        wrapper install_non_perl_dependencies
        wrapper install_perl_testonly_dependencies
        wrapper install_old_perl_dependencies
        wrapper install_webserver_dependencies
        wrapper install_selenium
        # install:
        wrapper install_perl_dependencies
        # before_script:
        wrapper init_cgi_config
        wrapper fix_cgis
        wrapper init_webserver_config
        wrapper start_webserver
        wrapper start_xserver
        wrapper init_webserver_environment
        wrapper start_selenium
        wrapper init_data
        # script:
        perl Makefile.PL && make test HARNESS_OPTIONS=j4
        # after_script:
        make distcheck
      if: "!startsWith(matrix.os,'windows-')"
  test_in_container:
    name: Docker tests with ${{ matrix.dist }}:${{ matrix.distver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dist:                       debian
            distver:                    jessie
            bbbike_test_skip_mapserver: 0
          - dist:                       debian
            distver:                    stretch
            bbbike_test_skip_mapserver: 1
          - dist:                       debian
            distver:                    buster
            bbbike_test_skip_mapserver: 1
    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        set -e
        sudo apt-get install -y libipc-run-perl
        ./miscsrc/docker-bbbike test --dist ${{ matrix.dist }} --distver ${{ matrix.distver }} --src local --jobs 8 --env BBBIKE_TEST_SKIP_MAPSERVER=${{ matrix.bbbike_test_skip_mapserver }}
